spring:
  application:
    name: lock
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lock_example
    username: test
    password: 1234
    hikari:
      maximum-pool-size: 40
  data:
    redis:
      host: localhost
      port: 6379